.github/workflows/cubic.yml
src/machine/machine_dao.rs

Adds GitHub actions to build, test, format and lint the code.
Changes:
- Added GitHub actions for cargo build, test, rustfmt and clippy
- Fixed a clippy error in MachineDao

ci: add github actions

---

src/machine/machine_dao.rs

Changes:
- Remove $HOME/.cache/cubic/machines/<machine> when machine is deleted

fix: remove cache files on machine deletion

---

src/machine/machine_dao.rs
src/util/filesystem.rs

Only enable KVM if supported
Changes:
- Introduced util::is_writable() function
- Enable KVM only if /dev/kvm is writable when VM is started

feat: check for kvm support

---

src/error.rs
src/image/image_fetcher.rs
src/image/image_name.rs
src/main.rs

Abort and show error when image cannot be downloaded
Changes:
- Added Error::ImageDownloadFailed
- Check return code of wget in ImageFetcher
- Added to_id() method to ImageName
- Print error message on ImageDownloadFailed

fix: show error when image download fails

---

snapcraft.yaml
src/machine/machine_dao.rs

Changes:
- Added runtime dependencies: qemu-system-gui, qemu-system-modules-spice, qemu-system-modules-opengl, libgtk-4-dev
- Added snap permissions: wayland, x11, desktop, desktop-legacy, opengl
- Set QEMU_MODULE_DIR environment variable for snap

feat: add display permission for snap

---

src/error.rs
src/machine/machine_dao.rs
src/util/env.rs

Changes:
- Store runtime information in volatile directory (XDG_RUNTIME_DIR)
- Rename UnsetHomeVar in UnsetEnvVar
- Implemented get_xdg_runtime_dir()

feat: relocate runtime dir

---

docs/install/snap.md
snapcraft.yaml
src/commands/scp.rs
src/commands/ssh.rs
src/commands/start.rs
src/error.rs
src/machine.rs
src/machine/machine_dao.rs
src/main.rs
src/ssh_cmd.rs
src/ssh_cmd/port_checker.rs
src/ssh_cmd/scp.rs
src/ssh_cmd/ssh.rs
src/util.rs
src/util/qemu.rs

Changes:
- Relocated all SSH related code under src/ssh_cmd
- Use SSH keys from user's home directory and the snap home directory
- Added ssh-keys interface to snap
- Removed ssh-keygen invocation and display error message if no keys were found
- Renamed SSHClient in PortChecker
- Added unit tests
- Updated snap install documentation

feat: revamped ssh implementation

---

src/commands/sh.rs
src/util/terminal.rs

The new terminal implementation terminates the threads cleanly and keeps the stdout in a consistant state after exit.

refactor: revamped the terminal implementation

---

src/util/qemu.rs

Starting an instance no longer requires the user to have SSH keys as instances may be accessed via serial without SSH.

fix: remove ssh key requirement

---

src/util/qemu.rs

Set the default password for the cubic user to 'cubic' in order to allow login via console.

feat: set cubic user default password to enable console login

---

src/commands/image.rs

Added new image subcommand "info". The info subcommand shows detailed information about a virtual machine image.
Example:
$ cubic image info debian:bookworm
Vendor:   debian
Codename: bookworm
Version:  12
URL:      https://cloud.debian.org/images/cloud/bookworm/latest/debian-12...

feat: add image info subcommand

---

src/commands/command_dispatcher.rs
src/commands/image.rs
src/commands/instance.rs
src/commands/mount.rs
src/commands/net/hostfwd.rs

Added shorter aliases to commands:
- cubic ls              -> cubic list
- cubic image ls        -> cubic image list
- cubic image del       -> cubic image rm
- cubic instance ls     -> cubic instance list
- cubic instance del    -> cubic instance rm
- cubic mount ls        -> cubic mount ls
- cubic mount del       -> cubic mount rm
- cubic net hostfwd ls  -> cubic net hostfwd ls
- cubic net hostfwd del -> cubic net hostfwd del

feat: add common command aliases

---

Cargo.toml
README.md
docs/usage/list.md
src/commands/image.rs
src/image/image_dao.rs

Changes:
- Show all available images by default in 'image ls' command
- Hide and mark -a/-all flag in 'image ls' command as deprecated
- Hide and mark 'image rm/del' command as deprecated
- Added 'image prune' command to clear local image cache
- Updated documentation

feat: revise image subcommands

---

src/commands/instance_add_command.rs
src/error.rs
src/image/image_dao.rs
src/util/qemu.rs

Use better default settings for new instances:
- Set CPUS to 4 instead of 1
- Set memory to 4G instead of 1G
- Set disk capacity to 100G instead of the original distro size Also cleaned up the get disk capacity functionality that is no longer used.

fix: improve standard machine instance settings

---

docs/reference/rm.rst
src/commands/command_dispatcher.rs
src/commands/instance.rs
src/commands/instance_remove_command.rs

Allow to delete a virtual machine instance without an interactive confirmation.

feat: add --yes option to 'rm' command

---

docs/reference/start.rst
docs/reference/stop.rst
src/commands/command_dispatcher.rs
src/commands/console.rs
src/commands/instance_remove_command.rs
src/commands/restart.rs
src/commands/ssh.rs
src/commands/start.rs
src/commands/stop.rs

Do not wait anymore by default for the virtual machine instance to be started or stopped. Instead the user need to pass the -w/--wait flag if the waiting is desired.

feat: add --wait flag to start and stop commands

---

docs/reference/add.rst
docs/reference/run.rst
src/commands/instance_add_command.rs
src/commands/instance_run_command.rs
src/instance.rs
src/instance/port_forward.rs

Added a new command line argument (-p/--port) to the commands 'add' and 'run' to allow port forwarding from the guest to the host.
Examples of the new argument:
Create an instance with the name 'example1' and forward the guest port 80 to
the host port 8000.
$ cubic add --image debian:bookworm -p 8000:80 example1
Create an instance with the name 'example2'and forward the guest tcp port 22
to the host ip 127.0.0.1 and host tcp port 9000.
$ cubic add --image debian:bookworm -p 127.0.0.1:9000:22/tcp example2
Create an instance with the name 'example3' and forward the guest ports 80
and 81 to the host ports 8000 and 8001.
$ cubic add --image debian:bookworm -p 8000:80 -p 8001:81 example1

feat: add port forwarding argument to add/run commands

---

src/commands/instance_add_command.rs
src/commands/instance_info_command.rs
src/commands/instance_modify_command.rs
src/commands/net/hostfwd.rs
src/emulator.rs
src/instance.rs
src/instance/port_forward.rs

For security reasons treat the port forwarding rule '-p 8000:80' as '-p 127.0.0.1:8000:80/tcp' and not as '-p 0.0.0.0:8000:80/tcp'. This prevents that users expose virtual machine instance ports by accidents to their local area network.

fix: expose forwarded ports without an ip on localhost

---

src/env/environment_factory.rs

Use the following default paths under Linux if the XDG environment variables are not found:
XDG_DATA_HOME   => $HOME/.local/share
XDG_CACHE_HOME  => $HOME/.cache
XDG_RUNTIME_DIR => /run/user/$UID

feat: use default paths if xdg environment is undefined

---

src/commands/instance_add_command.rs
src/commands/instance_clone_command.rs
src/commands/instance_rename_command.rs
src/commands/instance_run_command.rs
src/commands/instance_show_command.rs
src/instance.rs
src/instance/instance_name.rs

Restricted instance names to unicode letters, numbers, underlines and dashes to avoid problems with OS file names.

feat: add instance name validation

---

docs/reference/add.rst
docs/reference/clone.rst
docs/reference/console.rst
docs/reference/cubic.rst
docs/reference/image.rst
docs/reference/ls.rst
docs/reference/modify.rst
docs/reference/prune.rst
docs/reference/rename.rst
docs/reference/restart.rst
docs/reference/rm.rst
docs/reference/run.rst
docs/reference/scp.rst
docs/reference/show.rst
docs/reference/ssh.rst
docs/reference/start.rst
docs/reference/stop.rst
src/commands/command_dispatcher.rs
src/commands/instance_console_command.rs
src/commands/instance_remove_command.rs
src/commands/instance_restart_command.rs
src/commands/instance_run_command.rs
src/commands/instance_scp_command.rs
src/commands/instance_ssh_command.rs
src/commands/instance_start_command.rs
src/commands/instance_stop_command.rs
src/error.rs
src/instance/instance_store_mock.rs
src/main.rs

Removed duplicated code by defining the --verbose and --quiet flag globally.

refactor: define verbose and quiet as global flags

---

Cargo.toml
README.md
docs/howto/add_instance.rst
docs/index.rst
docs/reference/add.rst
docs/reference/cubic.rst
src/commands.rs
src/commands/command_dispatcher.rs
src/commands/create_instance_command.rs
src/commands/instance_run_command.rs

Renamed the 'add' command in 'create'. The old command name remains available for backward compatiblity.

feat: rename command 'add' in 'create'

---

src/commands/list_port_command.rs

For consistency with the other list commands, make the first letter of the `cubic ports` command uppercase.

fix: table heading inconsistency #189

---

src/actions.rs
src/actions/create_instance_action.rs
src/commands/command_dispatcher.rs
src/commands/create_instance_command.rs
src/commands/instance_run_command.rs
src/fs.rs
src/image/image_dao.rs
src/image/image_store.rs
src/image/image_store_mock.rs
src/instance/instance_dao.rs
src/view/spinner_view.rs

The instance creation is improved by:
- Always create an uncompressed qcow2 file for higher performance
- Make sure that if the creation process fails it does not result in a corrupt instance
- Show a visual spinner during the creation process

feat: improve instance creation process
