README.md

Added run-time dependencies to README

docs: add run-time dependencies

---

src/commands/add.rs
src/commands/config.rs
src/machine.rs
src/machine/machine_dao.rs
src/main.rs

Changes:
- Added flag to enable/disable the sandbox via config command
- Sandbox is disabled by default

feat: allow to disable the sandbox

---

src/commands/list.rs
src/machine/machine_dao.rs
src/util/ssh.rs

Added MachineState with the states stopped, starting and running.
Changes:
- Added enum MachineState
- Added method get_state() to MachineDAO
- Added util::SSHClient and SSHClient::try_connect()
- Added machine state to list command output

feat: added machine state

---

src/commands/ssh.rs
src/error.rs
src/machine/machine_dao.rs
src/main.rs

Improved user experience while waiting for a machine to boot.
Changes:
- Added a message in the ssh command which shows the user how much time has passed
- Added derive PartialEq for MachineState
- Removed Error::ConnectionTimeout
- Removed error message for Error::ConnectionTimeout

feat: improve ssh connection command

---

src/commands/add.rs
src/commands/list.rs
src/error.rs
src/image.rs
src/image/image_dao.rs
src/image/image_factory.rs
src/image/image_fetcher.rs
src/image/image_name.rs
src/main.rs
src/util/qemu.rs

Changes:
- Added ImageFactory
- Added GetCapacityFailed
- Added ImageDao.get_capacity() and ImageDao.copy_file()
- Added Image.to_image_name()
- Removed ImageName.from_file_name()
- Switch to minimal Ubuntu Cloud images
- Restart image downlaod if previous attempt was interrupted

feat: improved image handling

---

src/commands/add.rs
src/commands/list.rs
src/image/image_dao.rs
src/main.rs
src/util/qemu.rs

Changes:
- Improved list images printing
- Added --all flag to list command
- Renamed ImageDao.get_capacity() in ImageDao.get_disk_capacity()
- Added ImageDao.get_disk_size()
- Added util::get_disk_size()

feat: improved list image output

---

CONTRIBUTING.md
README.md
docs/build.md
docs/install/snap.md
docs/usage/add_delete.md
docs/usage/configure.md
docs/usage/copy_mount.md
docs/usage/list.md
docs/usage/rename_clone.md
docs/usage/sh.md
docs/usage/start_stop.md

Changes:
- Moved usage documentation under docs/usage/*
- Moved installation documentation under docs/install/*
- Moved build documenation to docs/build.md
- Moved contribution documentation to CONTRIBUTING.md
- Updated documentation

docs: improve documentation

---

README.md
snapcraft.yaml

Changes:
- Fixed snapcraft.yaml version
- Fixed summary in snapcraft.yaml
- Fixed descprition in snapcraft.yaml
- Fixed typo in README.md

fix: update snapcraft.yaml with current version and documentation

---

snapcraft.yaml
src/machine/machine_dao.rs

Changes:
- Added gnome-extension to reuse UI libraries
- Added virgl library
- Disabled QEMU command output
- Removed libraries already present in gnome extensions
- Removed LD_LIBRARY_PATH overright

feat: improve display support for snap

---

src/commands/add.rs
src/commands/config.rs
src/machine.rs
src/machine/machine_dao.rs

Changes:
- Added config option for GPU acceleration
- Switched default display output to GTK

feat: add gpu config

---

snapcraft.yaml
src/cli.rs
src/commands/add.rs
src/commands/config.rs
src/machine.rs
src/machine/machine_dao.rs

Changes:
- Removed unused libraries also for non-amd64 systems
- Removed unused bubblewrap dependency

refactor: reduce snap size

---

src/emulator.rs
src/machine/machine_dao.rs
src/main.rs

QEMU related code was moved from MachineDao to Emulator.

refactor: added emulator

---

README.md
src/commands/image.rs
src/image/image_factory.rs
src/util/qemu.rs

Changes:
- Added ArchLinux image
- Reorderd images alphabetically
- Remove bootcmds from user-data.yaml if empty
- Change cloud-init package from openssh-server to openssh

feat: add archlinux guest image

---

src/cli.rs
src/commands/scp.rs

Changes:
- Fixed scp file transfer in snap
- Added verbose flag to scp command
- Added scp-args to scp command

fix: resolve permission denied in snap with scp

---

src/commands/restart.rs
src/commands/sh.rs
src/commands/ssh.rs
src/commands/start.rs
src/commands/stop.rs
src/main.rs
src/view.rs
src/view/instance_state_change_view.rs
src/view/timer_view.rs

Changes:
- Added TimerView
- Added InstanceStateChangeView
- Use InstanceStateChangeView in start, stop, restart, ssh and sh commands

feat: improved user experience for starting and stopping instances

---

docs/usage/hostfwd.md
src/commands/image.rs
src/commands/instance.rs
src/commands/net.rs
src/commands/net/hostfwd.rs
src/view.rs
src/view/table_view.rs

Changes:
- Added TableView
- Use TableView in "list", "image list" and "hostfwd list" subcommands
- Display the host port forwarding rules of all instance in "hostfwd list" command
- Updated hostfwd documentation

feat: improve printing of tables

---

src/qemu/qmp.rs

Set QMP read/write timemout to 10 ms and use an id to identify QMP requests and responses.

feat: improve qmp message handler

---

.github/workflows/cubic.yml
Dockerfile
taskfile.yml

Added a Dockerfile to build an image with all necessary tooling in order to achive the same results on different hosts.

feat: add docker build image

---

src/commands/scp.rs
src/ssh_cmd/scp.rs

Implemented file and directory copies between two instances. Example:
cubic scp source_machine:~/testfile target_machine:~/

feat: allow scp copies between two instances

---

src/commands/image.rs

Show the actual image names in the image list view.

feat: improve image list view

---

src/commands/image.rs
src/image.rs
src/image/image_dao.rs
src/image/image_factory.rs
src/util/qemu.rs
src/web/web_client.rs

Replace the static list of virtual machine images with a web crawler that
automatically searches for available images.

Dynamically Generate Image List with Web Crawler 

---

Cargo.lock
Cargo.toml
snapcraft.yaml
src/commands/image.rs
src/image/image_dao.rs
src/image/image_factory.rs
src/image/image_fetcher.rs
src/web/web_client.rs

Improve HTTP transfer speed:
- Use Rustls instead OpenSSL
- Enable Gzip and Brotli compression
- Define HTTP client timeout

feat: optimize http communication

---

src/image.rs
src/image/image_factory.rs
src/util/env.rs

Cache result of the image web crawler to reduce network usage and improve the cli response time.

feat: add image cache

---

src/commands/instance_add_command.rs
src/commands/instance_run_command.rs

Reused the InstanceAddCommand in InstanceRunCommand to remove duplicated code.

refactor: clean up run command class

---

src/commands/create_instance_command.rs
src/commands/instance_modify_command.rs
src/commands/instance_show_command.rs
src/commands/list_image_command.rs
src/commands/list_instance_command.rs
src/error.rs
src/instance/instance_dao.rs
src/model.rs
src/model/data_size.rs
src/util/qemu.rs
src/view/transfer_view.rs

Introduced the DataSize struct to parse and format data size information.

Improve Error Message for Invalid Data Size Input
